### ISSUE TITLE
Show Tabs Item on the basis of roles

### ISSUE THREAD

**Issue by humayunjavaid** [vildanbina/livewire-tabs#4]
How can we implement role base tab hide and show?

**Comment by vildanbina** [comment]
You can customize the `TabComponent` class in the `tabs()` method. There you can apply any kind of filter to the tabs you want to return

**Comment by humayunjavaid** [comment]
One more issue 

i have made location tab but on submit General tab 's save function calls? how to call Location tab save method to save location form fields?

for now i override save function like following


`public function save(): void
    {

        $this->callHook('beforeValidate');

        $this->tabsValidation();

        $this->callHook('afterValidate');

        $state = $this->mutateStateBeforeSave($this->getState());

        $this->callHook('beforeSave');

        $this->getCurrentTab()->save($state);


        $this->callHook('afterSave');
    }`

**Comment by vildanbina** [comment]
Please refer to [this link](https://github.com/vildanbina/livewire-tabs?tab=readme-ov-file#creating-a-tab-item). Each tab class should have a designated save method, which will be called sequentially when the form is submitted
