### ISSUE TITLE
Hooks Not Working

### ISSUE THREAD

**Issue by humayunjavaid** [vildanbina/livewire-tabs#5]
Too few arguments to function App\Tabs\Lead\General::onTabIn(), 0 passed in 
/vendor/vildanbina/livewire-tabs/src/Concerns/HasHooks.php on line 13 and exactly 2 expected

`public function onTabIn($name ,$value)
    {
        dd($name);
    }`

**Comment by vildanbina** [comment]
@humayunjavaid the issue has already been fixed in version 1.3. Please revisit the README.md to get the latest updates
